version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "16"
  commands:
    # Install poetry
    - pip install poetry==2.0.1
    # Install poetry dependencies
    - poetry install --with docs
    # Install and build Antora documentation
    - npm install -g @antora/cli @antora/site-generator
    - npm install
    - antora docs/antora-playbook.yml

# Additional formats
formats:
  - pdf
  - epub