from pathlib import Path

TESTS_PATH = Path(__file__).parent.resolve()

TEST_DATA_PATH = TESTS_PATH / "test_data"
TEST_DATA_CORE_MODULE_PATH = TEST_DATA_PATH / "core"
TEST_DATA_MPV1_MODULE_PATH = TEST_DATA_PATH / "mapping_package_v1"
TEST_DATA_MPV2_MODULE_PATH = TEST_DATA_PATH / "mapping_package_v2"
TEST_DATA_MPV3_MODULE_PATH = TEST_DATA_PATH / "mapping_package_v3"
TEST_DATA_MAPPING_SUITE_MODULE_PATH = TEST_DATA_PATH / "mapping_suite"

TEST_DATA_MAPPING_PACKAGES_REPO_PATH = TEST_DATA_CORE_MODULE_PATH / "ted-rdf-mapping-eforms-light"
TEST_DATA_MAPPING_PACKAGES_V3_REPO_PATH = TEST_DATA_CORE_MODULE_PATH / "mapping_packages_v3_repo"
TEST_DATA_CORRUPTED_MAPPING_PACKAGE_PATH = TEST_DATA_CORE_MODULE_PATH / "corrupted_package.zip"

TEST_DATA_EXAMPLE_EFORMS_MAPPING_PACKAGE_PATH = TEST_DATA_MPV2_MODULE_PATH / "package_eforms_29_v1.9_changed.zip"
TEST_DATA_EXAMPLE_EFORMS_MAPPING_PACKAGE_MODEL_PATH = TEST_DATA_MPV2_MODULE_PATH / "package_eforms_29_v1.9_changed_model.json"
TEST_DATA_EXAMPLE_EFORMS_MAPPING_PACKAGE_FOLDER_PATH = TEST_DATA_MPV2_MODULE_PATH / "package_eforms_29_v1.9_changed"

TEST_DATA_EXAMPLE_SF_MAPPING_PACKAGE_PATH = TEST_DATA_MPV1_MODULE_PATH / "package_F22_changed.zip"
TEST_DATA_EXAMPLE_SF_MAPPING_PACKAGE_MODEL_PATH = TEST_DATA_MPV1_MODULE_PATH / "package_F22_changed_model.json"
TEST_DATA_EXAMPLE_SF_MAPPING_PACKAGE_FOLDER_PATH = TEST_DATA_MPV1_MODULE_PATH / "package_F22_changed"


TEST_DATA_EXAMPLE_V3_MAPPING_PACKAGE_PATH = TEST_DATA_MPV3_MODULE_PATH / "package_eforms_sdk1.13_epo4.0_changed.zip"
TEST_DATA_EXAMPLE_V3_MAPPING_PACKAGE_MODEL_PATH = TEST_DATA_MPV3_MODULE_PATH / "package_eforms_sdk1.13_epo4.0_changed.json"
TEST_DATA_EXAMPLE_V3_MAPPING_PACKAGE_FOLDER_PATH = TEST_DATA_MPV3_MODULE_PATH / "package_eforms_sdk1.13_epo4.0_changed"

TEST_DATA_EXAMPLE_MAPPING_SUITE_FOLDER_PATH = TEST_DATA_MAPPING_SUITE_MODULE_PATH / "eforms_config"
TEST_DATA_EXAMPLE_MAPPING_SUITE_ARCHIVE_PATH = TEST_DATA_MAPPING_SUITE_MODULE_PATH / "eforms_config.zip"
TEST_DATA_EXAMPLE_MAPPING_SUITE_CONFIG_FILE = TEST_DATA_EXAMPLE_MAPPING_SUITE_FOLDER_PATH / "mapping_suite_config.json"

UNIT_TESTS_PATH = TESTS_PATH / "unit"
