site:
  title: Mapping Suite SDK test Documentation
  url: https://mapping-suite-sdk-test.readthedocs.io
  start_page: mapping-suite-sdk::index.adoc

content:
  sources:
    - url: ./..
      start_path: docs
      branches: HEAD
      edit_url: false

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''