name: Update badges

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  test:
    name: Pylint
    runs-on: ubuntu-latest

    steps:

    - name: Update PyLint Badge
      uses: Silleellie/pylint-github-action@v2.1
      with:
        lint-path: ./mssdk ./tests
        python-version: 3.12
        pylintrc-path: .pylintrc